services:
  pgvecto-rs:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    
    restart: always
    environment:
      PGUSER: ${PGVECTOR_PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGVECTOR_POSTGRES_PASSWORD:-14061c828dc6b4719767}
      POSTGRES_DB: ${PGVECTOR_POSTGRES_DB:-data}
      PGDATA: ${PGVECTOR_PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/pgvecto_rs/data:/var/lib/postgresql/data
    ports:
      - '0.0.0.0:9308:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proxynet

networks:
  proxynet:
    driver: bridge